import {Router} from "express";
import {getHealth} from "../controllers/health";
import { requireAuth } from "../middleware/auth";
import { getColleges } from "../controllers/colleges";
import { addCollege } from "../controllers/colleges";
import { addDepartment, getDepartments } from "../controllers/department";
import { getsemesters,addSemester } from "../controllers/semester";
import {getCourse,addCourse} from "../controllers/course";
import {getTopics,addTopic} from "../controllers/topics";
import { getSubtopics,addSubtopic } from "../controllers/subtopics";
import { register,login } from "../controllers/auth";
const router = Router();
router.get("/health", getHealth);
router.post("/auth/register",register);
router.post("/auth/login",login);
router.get("/colleges", requireAuth,getColleges);
router.post("/colleges", addCollege);
router.get("/departments", requireAuth,getDepartments);
router.post("/departments", addDepartment);
router.get("/semesters", requireAuth,getsemesters);
router.post("/semesters", addSemester);
router.get("/courses",requireAuth,getCourse);
router.post("/courses",addCourse);
router.get("/topics",requireAuth,getTopics);
router.post("/topics",addTopic);
router.get("/subtopics",requireAuth,getSubtopics);
router.post("/subtopics",addSubtopic);
export {router as healthRouter};